server:
  port: 8100

coingecko-api:
  base-url: https://api.coingecko.com/api/
  version: v3
  coin-market:
    path: coins/markets
    vs_currency: usd
    order: market_cap_desc
    per_page: 100
    page: 1
    sparkline: false